# -*- coding: utf-8 -*-
"""ATELIER 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQskFn0aoElGCyzvvRgaQdjS8skodzEB
"""

AOUFI AYMAN

Module : Langage de programmation

Enacdré par : Dr. EL AACHAK Lotfi

Atelier 2

"""1. Créer une liste en choisissant des éléments d'index impair dans la première liste et des
éléments d'index pair dans la seconde.

"""

l1 = [3, 6, 9, 12, 15, 18, 21]
l2 = [4, 8, 12, 16, 20, 24, 28]
l3 = []

for i in range(len(l1)):
    if i % 2 == 0:
        l3.append(l2[i])
    else:
        l3.append(l1[i])
print(l3)

"""2. Deviser la liste en 3 morceaux égaux et inverser chaque morceau"""

l = [11, 45, 8, 23, 14, 12, 78, 45, 89]
premier_morceau = [11, 45, 8]
deuxieme_morceau = [23, 14, 12]
troisieme_morceau = [78, 45, 89]

premier_morceau_inverse = premier_morceau[::-1]  # [8, 45, 11]
deuxieme_morceau_inverse = deuxieme_morceau[::-1]  # [12, 14, 23]
troisieme_morceau_inverse = troisieme_morceau[::-1]  # [89, 45, 78]

print(premier_morceau_inverse)
print(deuxieme_morceau_inverse)
print(troisieme_morceau_inverse)

"""3. Écrire un programme pour itérer une liste donnée et compter l'occurrence de chaque élément et
créer un dictionnaire pour montrer le nombre de chaque élément
"""

liste = [11, 45, 8, 11, 23, 45, 23, 45, 89]

#  stocker les résultats
resultats = {}

# compter l'occurrence de chaque élément
for element in liste:
  # si l'élément existe déjà dans le dictionnaire, on incrémente sa valeur
  if element in resultats:
    resultats[element] += 1
  # sinon, on l'ajoute au dictionnaire avec une valeur de 1
  else:
    resultats[element] = 1
print(resultats)

"""4. Trouver l'intersection (commune) de deux Sets et supprimez ces éléments du premier Set"""

L1 = {23, 42, 65, 57, 78, 83, 29}
L2 = {57, 83, 29, 67, 73, 43, 48}

#l'intersection des deux ensembles
intersection = L1 & L2  # {57, 83, 29}

# on supprime les éléments de l'intersection du premier ensemble
L1 -= intersection  # {23, 42, 65, 78}

print(intersection)
print(L1)

"""5. Itérer une liste donnée et vérifier si un élément donné existe en tant que valeur de clé dans
un dictionnaire. Sinon, supprimez-le de la liste
"""

L = [47, 64, 69, 37, 76, 83, 95, 97]

# on définit le dictionnaire
dic = {'Yassine':47, 'Imane':69, 'Mohammed':76, 'Abir':97}

# on itère sur la liste
for element in L:
  # on vérifie si l'élément existe en tant que valeur de clé dans le dictionnaire
  if element not in dic.values():
    # si l'élément n'existe pas, on le supprime de la liste
    L.remove(element)

print(L)